AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
Metrics/LineLength:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
